=== Matteogrf/healthcare-system-integration/trunk/ESBMediator/Data/MappedEvents.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://events.laboratory.unitn.it/"
	    xmlns:tns="http://events.laboratory.unitn.it/"
	    attributeFormDefault="qualified" elementFormDefault="qualified">

	<xsd:element name="DWH_SCHEMA" type="tns:DwhSchemaType"/>

	<xsd:complexType name="DwhSchemaType">
		<xsd:sequence>
		    <xsd:element name="EVENT_TYPE" type="tns:EventType" minOccurs="1" maxOccurs="1">
			</xsd:element>
			<xsd:element name="D_ASSISTITO" type="tns:AssistitoType" minOccurs="0" maxOccurs="1">
			</xsd:element>
			<xsd:element name="D_OPERATORE" type="tns:OperatoreType" minOccurs="0" maxOccurs="1">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>	
    
    <xsd:complexType name="EventType">
		<xsd:sequence>
			<xsd:element name="EVENT_COD" type="int" minOccurs="1" maxOccurs="1"></xsd:element>
			<xsd:element name="EVENT_DESCR" type="string" minOccurs="1" maxOccurs="1"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="OperatoreType">
		<xsd:sequence>
			<xsd:element name="OPERATORE_COD" type="int" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="NOME" type="string" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="COGNOME" type="string" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="POLO_COD" type="int" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="POLO_DESCR" type="string" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="ENTE_GESTORE_COD" type="int" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="ENTE_GESTORE_DESCR" type="string" minOccurs="0" maxOccurs="1"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="AssistitoType">
		<xsd:sequence>
			<xsd:element name="ID_ASSISTITO" type="int" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="ID_ANAGRAFE_LOCALE" type="int" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="MITTENTE_NOME_ENTE" type="string" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="MITTENTE_URL_ENTE" type="string" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="ANAG_URL_ENTE" type="string" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="ANAG_ID_ANAGRAFE" type="int" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="ID_ASS_SOC" type="int" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="HASH_COD" type="string" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="DATA_NASCITA" type="date" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="COMUNE_NASCITA_COD" type="int" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="COMUNE_NASCITA_DESCR" type="string" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="COMUNE_RESIDENZA" type="string" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="COMUNE_RESIDENZA_COD" type="int" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:element name="COMUNE_RESIDENZA_DESCR" type="string" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:element name="SESSO" type="string" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:element name="CAP" type="string" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:element name="STATO_CIVILE_COD" type="int" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:element name="STATO_CIVILE_DESCR" type="string" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:element name="NAZIONALITA_COD" type="int" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:element name="NAZIONALITA_DESCR" type="string" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:element name="CITTADINANZA_COD" type="int" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:element name="CITTADINANZA_DESCR" type="string" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:element name="POLO_COD" type="int" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:element name="POLO_DESCR" type="string" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:element name="GESTORE_COD" type="int" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:element name="GESTORE_DESCR" type="string" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:element name="INIZIO_PRESA_CARICO" type="date" minOccurs="0" maxOccurs="1" ></xsd:element>
			<xsd:element name="DATA_DOMANDA" type="date" minOccurs="0" maxOccurs="1" ></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</schema>

=== Matteogrf/healthcare-system-integration/ESBMediator/Data/mappedEventExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:DWH_SCHEMA xmlns:tns="http://events.laboratory.unitn.it/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://events.laboratory.unitn.it/ MappedEvents.xsd ">
  <tns:D_ASSISTITO>
    <tns:ID_ANAGRAFE_LOCALE>0</tns:ID_ANAGRAFE_LOCALE>
    <tns:MITTENTE_NOME_ENTE>tns:MITTENTE_NOME_ENTE</tns:MITTENTE_NOME_ENTE>
    <tns:MITTENTE_URL_ENTE>tns:MITTENTE_URL_ENTE</tns:MITTENTE_URL_ENTE>
    <tns:ANAG_URL_ENTE>tns:ANAG_URL_ENTE</tns:ANAG_URL_ENTE>
    <tns:ANAG_ID_ANAGRAFE>0</tns:ANAG_ID_ANAGRAFE>
    <tns:HASH_COD>tns:HASH_COD</tns:HASH_COD>
    <tns:DATA_NASCITA>2001-01-01</tns:DATA_NASCITA>
    <tns:COMUNE_NASCITA_COD>0</tns:COMUNE_NASCITA_COD>
    <tns:COMUNE_RESIDENZA_COD>0</tns:COMUNE_RESIDENZA_COD>
    <tns:SESSO>tns:SESSO</tns:SESSO>
    <tns:CAP>tns:CAP</tns:CAP>
    <tns:STATO_CIVILE_COD>0</tns:STATO_CIVILE_COD>
    <tns:STATO_CIVILE_DESCR>tns:STATO_CIVILE_DESCR</tns:STATO_CIVILE_DESCR>
    <tns:NAZIONALITA_COD>0</tns:NAZIONALITA_COD>
    <tns:NAZIONALITA_DESCR>tns:NAZIONALITA_DESCR</tns:NAZIONALITA_DESCR>
    <tns:CITTADINANZA_COD>0</tns:CITTADINANZA_COD>
    <tns:CITTADINANZA_DESCR>tns:CITTADINANZA_DESCR</tns:CITTADINANZA_DESCR>
    <tns:POLO_COD>0</tns:POLO_COD>
    <tns:POLO_DESCR>tns:POLO_DESCR</tns:POLO_DESCR>
    <tns:GESTORE_COD>0</tns:GESTORE_COD>
    <tns:GESTORE_DESCR>tns:GESTORE_DESCR</tns:GESTORE_DESCR>
  </tns:D_ASSISTITO>
  <tns:D_OPERATORE>
    <tns:POLO_COD>0</tns:POLO_COD>
    <tns:POLO_DESCR>tns:POLO_DESCR</tns:POLO_DESCR>
    <tns:ENTE_GESTORE_COD>0</tns:ENTE_GESTORE_COD>
    <tns:ENTE_GESTORE_DESCR>tns:ENTE_GESTORE_DESCR</tns:ENTE_GESTORE_DESCR>
  </tns:D_OPERATORE>
</tns:DWH_SCHEMA>
